version: "3.9"

services:
  staycon-back-prod:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: staycon-back-prod
    command: python stay_connected/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=stay_connected.settings
