# Generated by Django 5.1.1 on 2024-11-30 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='likes_count',
            field=models.IntegerField(default=0, verbose_name='Likes Count'),
        ),
    ]
