# Generated by Django 5.1.3 on 2024-12-01 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_answer_likes_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='likes_count',
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
