# Generated by Django 5.1.3 on 2024-12-02 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_remove_answer_likes_count_delete_like'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'ordering': ['-isCorrect']},
        ),
    ]
