# Generated by Django 5.1.3 on 2024-11-30 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='correct_answers',
            field=models.IntegerField(default=0, verbose_name='Correct Answers'),
        ),
        migrations.AddField(
            model_name='user',
            name='rating',
            field=models.IntegerField(default=0, verbose_name='Rating'),
        ),
    ]
