# Generated by Django 5.1.3 on 2024-12-01 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_user_first_name_alter_user_last_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='correct_answers',
        ),
        migrations.AddField(
            model_name='user',
            name='my_answers',
            field=models.IntegerField(default=0, verbose_name='Answers'),
        ),
    ]
