name: Docker CI/CD

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    name: Build & Test
    runs-on: self-hosted

    steps:
      - name: Fix Repo Permissions
        run: |
          sudo chown -R $USER:$USER ${{ github.workspace }}
          sudo chmod -R u+rwX ${{ github.workspace }}

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Django Test
        env:
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          POSTGRES_HOST: ${{ secrets.POSTGRES_HOST }}
          POSTGRES_PORT: ${{ secrets.POSTGRES_PORT_DEV }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
          
        run: |
          python stay_connected/manage.py test

      - name: Build Docker Images
        run: |
          docker compose build

      - name: Test & Cleanup
        run: |
          docker compose down &&
          docker compose up -d &&
          docker image prune -af &&
          docker builder prune

  deploy:
    name: Deploy to Production Server
    needs: build
    runs-on: self-hosted
    environment:
      name: production
      url: https://stayconnected.lol/api/

    env:
      SSH_SERVER: ${{ vars.SSH_SERVER }}
      DEPLOY_DIR: ${{ vars.DEPLOY_DIR }}
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

    steps:
      - name: Setup SSH Key
        run: |
          set -e  # Exit immediately if a non-zero status
          echo "${SSH_PRIVATE_KEY}" > ~/id_ed25519
          chmod 600 ~/id_ed25519

      - name: Deploy via SSH
        run: |
          ssh -i ~/id_ed25519 -o StrictHostKeyChecking=no root@${SSH_SERVER} "
            cd ${DEPLOY_DIR} &&
            git pull &&
            docker compose build &&
            docker compose down &&
            docker compose up -d &&
            docker image prune -af &&
            docker builder prune -af
          "

      - name: Cleanup SSH Key
        run: |
          # Runner SSH private key remove
          rm -f ~/id_ed25519
